baseURL: https://blanka-mori-portfolio.netlify.app/
languageCode: en-us
title: Blanka Móri
theme: personal-web
copyright: © Edna West
googleAnalytics: ''
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
params:
  accentColor: '#FD3519'
  assets:
    customCSS: ''
    favicon: ''
  breadcrumb: yes
  contact:
    email: ''
    text: ''
  intro:
    main: 'Hi, I''m Blanka :wave:'
    sub: I'm a Data Analyst
  main:
    latestPublishHeader: My Latest Project
  mainSections: portfolio
  notFound:
    gopher: /images/gopher.png
    h1: Bummer!
    p: It seems that this page doesn't exist.
  rendererSafe: no
  sections:
    portfolio: project
    post: article
  sidebar:
    backgroundImage: /images/back8.jpeg
    gradientOverlay: ''
    logo: /images/profil7.jpg
  social:
    #codepen: https://codepen.io/
    #facebook: https://www.facebook.com/
    #github: https://github.com/
    #gitlab: https://gitlab.com/
    #instagram: https://www.instagram.com/
    #keybase: https://keybase.io/
    linkedin: https://www.linkedin.com/in/blanka-m%C3%B3ri-b74613230/
    #medium: https://medium.com/
    #twitter: https://twitter.com/
    #youtube: https://www.youtube.com/
taxonomies:
  design: designs
  tech: techs
blackfriday:
  hrefTargetBlank: yes
menu:
  main:
    - identifier: about
      name: About
      title: About section
      url: /about/
      weight: -120
    - identifier: portfolio
      name: Portfolio
      title: Portfolio
      url: /portfolio/
      weight: -110
   # - identifier: blog
  #  name: Post
   #   title: Blog section
    #  url: /post/
     # weight: -100
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: yes
    respectDoNotTrack: yes
    useSessionStorage: no
  twitter:
    disable: no
    enableDNT: yes
    simple: no
markup:
  goldmark:
    renderer:
      unsafe: yes
